conf/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('tmc.urls'))
]

tmc/urls.py
from django.urls import path, include
from django.conf.urls import url
from tmc.views import tmc

urlpatterns = [
    url(r'^$', tmc, name="tmc"),
]

tmc/models.py
from django.db import models

# Create your models here.

class Tmc(models.Model):
    """Modelo de la TMC
    
    Arguments:
        models {Object}
    """
    plazo = models.IntegerField('Plazo en dias', null=False, blank=False)
    monto = models.FloatField('Monto en UF', null=False, blank=False)
    fecha_tmc = models.DateField('Fecha de consulta TMC', null=False, blank=False)

tmc/forms.py
from django import forms
from tmc.models import Tmc



class TmcForm(forms.ModelForm):
    """Formulario para la TMC
    
    Arguments:
        forms {Object}
    """

    class Meta:
        model = Tmc
        fields = ('plazo', 'monto', 'fecha_tmc')

    def __init__(self, *args, **kwargs):
        super(TmcForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': self.fields[field].label 
            }) 
            self.fields[field].label = ''

tmc/views.py
import requests
from django.shortcuts import render
from django.http import HttpResponse
from conf.settings import TMC_API_KEY
from tmc.constantes import BASE_TMC_URL_API
from tmc.forms import TmcForm
from tmc.utils import get_tmc


def tmc(request):
    """Funcion que retorna el view de la TMC
    
    Arguments:
        request {Object}
    
    Returns:
        [Object] -- retorna el render con los parametros
    """
    response = ''
    error = ''
    if request.method == 'POST':
        form = TmcForm(request.POST)
        if form.is_valid():
            try:
                fecha_tmc = str(form.cleaned_data['fecha_tmc'])
                tmc_año = fecha_tmc.split('-')[0]
                tmc_mes = fecha_tmc.split('-')[1]
                url = '{}{}/{}?apikey={}&formato=json'.format(BASE_TMC_URL_API,tmc_año,tmc_mes,TMC_API_KEY)
                get_response = requests.get(url)
                response_json = get_response.json()
                if not response_json.get('CodigoHTTP'):      
                    data = {
                        'plazo': form.cleaned_data['plazo'],
                        'monto': form.cleaned_data['monto']
                    }
                    response = get_tmc(response_json['TMCs'], **data)
                else:
                    error =  response_json['Mensaje']   
            except requests.exceptions.RequestException as e:
                error = e 
            except requests.exceptions.Timeout as e:
                error = e
            except Exception as e:
                error = e
    else:
        form = TmcForm()
    
    return render(request,'tmc/tmc.html',{ 'response': response, 'form': form, 'error': error })

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <title>TMC</title>
</head>
<body>
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script>$('#id_fecha_tmc').datepicker();</script>
</body>
</html>

templates/tmc/tmc.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center mt-5 d-flex justify-content-center">
            <div class="col-md-4">
                <h1>Calculadora TMC</h1>
                <form class="mt-5" action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form | linebreaks }}
                    </div>
                    <input class="btn btn-primary" type="submit" value="Submit">
                </form>
            </div>
            
            <div>
                {% if response %}
                    <div class="alert alert-success" role="alert">
                        <h4 class="alert-heading">La TMC que corresponde es: </h4>
                        <p>{{response.Valor}}%</p>
                    </div>    
                {% endif %}
                {% if error%}
                    <div class="alert alert-danger" role="alert">
                        <h4 class="alert-heading"> Ha ocurrido un error</h4>
                        <p>{{error}}</p>
                    </div>    
                {% endif %}

            </div>
        </div>
    </div>    
</div>
{% endblock %}